# Generated by Django 4.2.7 on 2025-07-14 08:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('otros_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('gastos_fijos', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ahorro_mensual', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ahorro_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('score_crediticio', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimulacionCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HIPOTECARIO', 'Crédito Hipotecario'), ('AUTOMOTRIZ', 'Crédito Automotriz')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('valor_propiedad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('enganche_porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tasa_interes_anual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('plazo_anos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('gastos_adicionales', models.DecimalField(decimal_places=2, default=0, help_text='Seguros, notaría, etc.', max_digits=10)),
                ('fecha_simulacion', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones', to='finanzas.perfilfinanciero')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='finanzas.perfilfinanciero')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CASA', 'Compra de Casa'), ('AUTO', 'Compra de Auto'), ('OTRO', 'Otro')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plazo_meses', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='finanzas.perfilfinanciero')),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TARJETA', 'Tarjeta de Crédito'), ('PERSONAL', 'Préstamo Personal'), ('ESTUDIANTIL', 'Préstamo Estudiantil'), ('AUTO', 'Préstamo Automotriz'), ('HIPOTECA', 'Hipoteca'), ('OTRO', 'Otro')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pago_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_inicio', models.DateField()),
                ('plazo_meses', models.IntegerField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='finanzas.perfilfinanciero')),
            ],
        ),
    ]
