# Generated by Django 4.2.11 on 2025-07-20 00:43

from decimal import Decimal
from django.conf import settings
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finanzas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Cuenta"
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CHECKING", "Cuenta de Cheques"),
                            ("SAVINGS", "Cuenta de Ahorros"),
                            ("CREDIT_CARD", "Tarjeta de Crédito"),
                            ("INVESTMENT", "Inversión"),
                            ("LOAN", "Préstamo"),
                            ("CASH", "Efectivo"),
                        ],
                        default="CHECKING",
                        max_length=20,
                        verbose_name="Tipo de Cuenta",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("MXN", "Peso Mexicano"),
                            ("USD", "Dólar Estadounidense"),
                            ("EUR", "Euro"),
                        ],
                        default="MXN",
                        max_length=3,
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Saldo Inicial",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Saldo Actual",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta",
                "verbose_name_plural": "Cuentas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Presupuesto"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Mensual"),
                            ("QUARTERLY", "Trimestral"),
                            ("YEARLY", "Anual"),
                        ],
                        default="MONTHLY",
                        max_length=10,
                        verbose_name="Período",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de Fin")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Monto Total",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del ícono (ej: fas fa-shopping-cart)",
                        max_length=50,
                        verbose_name="Ícono",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6c757d",
                        help_text="Color en formato hexadecimal",
                        max_length=7,
                        verbose_name="Color",
                    ),
                ),
                (
                    "is_income",
                    models.BooleanField(default=False, verbose_name="Es Ingreso"),
                ),
                (
                    "is_expense",
                    models.BooleanField(default=True, verbose_name="Es Gasto"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="finanzas.category",
                        verbose_name="Categoría Padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("INCOME", "Ingreso"),
                            ("EXPENSE", "Gasto"),
                            ("TRANSFER", "Transferencia"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Transacción",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descripción"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="Es Recurrente"),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="Cancelada"),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="receipts/%Y/%m/",
                        verbose_name="Recibo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="finanzas.account",
                        verbose_name="Cuenta",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finanzas.category",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "destination_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transfers",
                        to="finanzas.account",
                        verbose_name="Cuenta Destino",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción",
                "verbose_name_plural": "Transacciones",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="finanzas_tr_user_id_95561c_idx"
                    ),
                    models.Index(
                        fields=["account", "transaction_type"],
                        name="finanzas_tr_account_c4d2d8_idx",
                    ),
                    models.Index(
                        fields=["category"], name="finanzas_tr_categor_a27b38_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nombre del Reporte"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("INCOME_EXPENSE", "Ingresos vs Gastos"),
                            ("CATEGORY_ANALYSIS", "Análisis por Categoría"),
                            ("ACCOUNT_BALANCE", "Balance de Cuentas"),
                            ("BUDGET_VS_ACTUAL", "Presupuesto vs Real"),
                            ("CASH_FLOW", "Flujo de Efectivo"),
                            ("NET_WORTH", "Patrimonio Neto"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Reporte",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de Fin")),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="Parámetros",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="Datos del Reporte",
                    ),
                ),
                (
                    "is_saved",
                    models.BooleanField(default=False, verbose_name="Guardado"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "report_type"],
                        name="finanzas_re_user_id_547e95_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="finanzas_re_start_d_7edd53_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BudgetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Monto Asignado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="finanzas.budget",
                        verbose_name="Presupuesto",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finanzas.category",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Presupuesto",
                "verbose_name_plural": "Categorías de Presupuesto",
                "unique_together": {("budget", "category")},
            },
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["user", "is_active"], name="finanzas_bu_user_id_58cc1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["start_date", "end_date"], name="finanzas_bu_start_d_e07340_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["user", "is_active"], name="finanzas_ac_user_id_bc2c7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["account_type"], name="finanzas_ac_account_6b7246_idx"
            ),
        ),
    ]
