# Generated by Django 4.2.11 on 2025-07-20 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0002_account_budget_category_transaction_report_and_more"),
    ]

    operations = []
