# Generated by Django 4.2.11 on 2025-07-20 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0003_auto_20250719_1844"),
    ]

    operations = []
